spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1/translation
#    url: jdbc:postgresql://10.20.4.67/translation
    username: translation
    password: translation
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    generate-ddl: true
    show-sql: true
    database: postgresql
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: "2MB"
logging:
  level:
    ROOT: info
  register-shutdown-hook: true
server:
  port: 8080
management:
  endpoint:
    health:
      enabled: true
      show-details: never